### ISSUE TITLE
Spam classification examples

### ISSUE THREAD

**Issue by bkmgit** [mlpack/examples#102]
Would like to add some spam classification examples using ML Pack. Would this be useful? Some related work [here](https://fedoramagazine.org/spam-classification-with-ml-pack/)

**Comment by zoq** [comment]
@bkmgit absolutely great idea

**Comment by bkmgit** [comment]
Started on this, see #112 

A related issue is https://github.com/mlpack/mlpack.org/issues/28

**Comment by rcurtin** [comment]
Oops, no need to close this until we get #112 merged. (Hopefully soon!) :)
