### ISSUE TITLE
Error building the mnist_cnn and mnist_simple example 

### ISSUE THREAD

**Issue by Aakash-kaushik** [mlpack/examples#117]
When i try to build the mnist_cnn.cpp and the mnist_simple.cpp i get the following error which is same for both files.
the version of mlpack i have is: 3.2.2-3
```
mnist_cnn.cpp: In function ‘int main()’:
mnist_cnn.cpp:189:20: error: no matching function for call to ‘ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(main()::<lambda(const mat&)>)’
  189 |                   }));
      |                    ^
In file included from /usr/include/ensmallen.hpp:67,
                 from /usr/include/mlpack/methods/ann/ffn.hpp:33,
                 from mnist_cnn.cpp:20:
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:31:3: note: candidate: ‘ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(size_t)’
   31 |   EarlyStopAtMinLoss(const size_t patienceIn = 10) :
      |   ^~~~~~~~~~~~~~~~~~
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:31:35: note:   no known conversion for argument 1 from ‘main()::<lambda(const mat&)>’ to ‘size_t’ {aka ‘long unsigned int’}
   31 |   EarlyStopAtMinLoss(const size_t patienceIn = 10) :
      |                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note: candidate: ‘constexpr ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(const ens::EarlyStopAtMinLoss&)’
   21 | class EarlyStopAtMinLoss
      |       ^~~~~~~~~~~~~~~~~~
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note:   no known conversion for argument 1 from ‘main()::<lambda(const mat&)>’ to ‘const ens::EarlyStopAtMinLoss&’
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note: candidate: ‘constexpr ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(ens::EarlyStopAtMinLoss&&)’
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note:   no known conversion for argument 1 from ‘main()::<lambda(const mat&)>’ to ‘ens::EarlyStopAtMinLoss&&’
make: *** [<builtin>: mnist_cnn.o] Error 1
```

**Comment by Aakash-kaushik** [comment]
Hey i think i have a older version of ensmallen i just compared the early_stop_at_min_loss.hpp and they are different and the function is implemented in the new one. feel free to close this issue if this is the case.

**Comment by rcurtin** [comment]
@Aakash-kaushik I think that's exactly the issue here.  Make sure your version of ensmallen is up to date and I think there will be no issue. :+1:

Before I close this, though, can I ask how you installed ensmallen and what version you have installed?

**Comment by Aakash-kaushik** [comment]
Hey @rcurtin my ensmallen version was `2.11.3-1` and I installed it through the ubuntu focal source, can be found [here](https://packages.ubuntu.com/focal/libensmallen-dev).
And currently I am running the version `2.14.2` from the ensmallen site.

**Comment by rcurtin** [comment]
Ok, I see.  In this case this particular example requires at least `2.13.0`.  So, I see that is in Ubuntu groovy.  If you want, maybe you can file a bug asking for a backport to focal?  Alternately, maybe we can think about a way to update the documentation for this repository or add a check somehow to ensure that the user has a new enough version of ensmallen.  Let me know what you think.

**Comment by Aakash-kaushik** [comment]
I think the way to go for this will be to update our documentation for this repository and add a check, because i feel like asking for a backport to focal will take a long time to render this issue useless.
