### ISSUE TITLE
`mnist_batch_norm` fails with incorrect matrix multiply size

### ISSUE THREAD

**Issue by rcurtin** [mlpack/examples#131]
When you build the `mnist_batch_norm` example and run it after checking out the datasets as per the README, this is the output given:

```
$ ./mnist_batch_norm
Training ...
Epoch 1
5.12862 [====================================================================================================] 100% - ETA: 0s - loss: 5.12103
844/844 [====================================================================================================] 100% - 15s 18ms/step - loss: 5.12862
Validation loss: 27337.6.
...
Epoch 19
0.445508[====================================================================================================] 100% - ETA: 0s - loss: 0.444849
844/844 [====================================================================================================] 100% - 17s 20ms/step - loss: 0.445508
Validation loss: 11522.2.
Accuracy: train = 63.2407%, valid = 63.6106%
Predicting ...

error: matrix multiplication: incompatible matrix dimensions: 100x784 and 785x1
terminate called after throwing an instance of 'std::logic_error'
  what():  matrix multiplication: incompatible matrix dimensions: 100x784 and 785x1
Aborted
```

When this is fixed, `.travis.yml` can be updated to stop skipping this example.

**Comment by heisenbuug** [comment]
Hey @rcurtin, So when I ran the code locally it is working fine, so I think the issue is somewhere in the downloading and preprocessing of testing data step, we are getting one pixel extra(785), it should be 784(28*28). I will work on this issue.

**Comment by rcurtin** [comment]
Cool, thanks!  It might be that in `mnist_batch_norm.cpp`, the labels are not being removed from the training dataset or test dataset or something.

**Comment by heisenbuug** [comment]
Yea, the dataset that is being downloaded by the python script has an extra row which is not being removed by minst_batch_norm.cpp compared to the downloaded test file...
A simple change in mnist_batch_norm.cpp, the submat line for test file, passing correct parameters there should do the thing...

**Comment by heisenbuug** [comment]
@rcurtin What change do I have to make in `.travis.yml`?

**Comment by rcurtin** [comment]
Oh, if you take a look at the script in .travis.yml, it skips the `mnist_batch_norm` example.  Just remove that bit, then you'll be able to see that it runs `mnist_batch_norm` on Travis. :)

**Comment by heisenbuug** [comment]
Its done, check out the PR

**Comment by rcurtin** [comment]
#137 is merged, so this is fixed now.  Thanks @heisenbuug! :+1:
