### ISSUE TITLE
Problem in shebang line in "download_data_set.py"

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/examples#134]
When I tried to download the datasets by running `./download_data_set.py` on my Ubuntu20.04 machine, I got this error
Traceback (most recent call last):
  File "./download_data_set.py", line 11, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm

But when I tried `python3 download_data_set.py`, it worked.
So, the problem here is with selecting the correct python interpreter in the shebang line. By default it is selecting the python2 and the support for it is removed in ubuntu that is why it is having trouble finding the tqdm package.

An easy fix would be to replace "#!/usr/bin/python" with "#!/usr/bin/python3" but I am not sure if this would break something in any other OS. Or a better fix would be to write a wrapper script that will select the available interpreter itself.   
Please let me know any thoughts. 
Also, if there is a need to make any changes, then I will be happy work on it.

**Comment by zoq** [comment]
That depends on your system, from your message above it sounds like your default version is python2.7 and not python3? On my system python links to python3. So I'm not sure we should change the script here, you could update your default - https://unix.stackexchange.com/a/410851.

**Comment by RishabhGarg108** [comment]
Hey @zoq , changing my default version would be a better option. This didn't come to my mind. Thanks.
So, I should close this issue now.
