### ISSUE TITLE
Changing CNN weights

### ISSUE THREAD

**Issue by FabioMBB** [mlpack/examples#145]
Hi, 
I would like to change the weights of the FFN model used for the MNIST example.
I practically would like to manually set all the weights of the network (I know that it sounds strange...).

Can you guys please help me to do that?

Thank you very much in advance for your help,
Fabio

**Comment by FabioMBB** [comment]
Never mind, I found a way by using model.parameters().

Thank you so much anyway.

Fabio

**Comment by rcurtin** [comment]
Glad you got it sorted out!  And sorry for the slow response.  `model.parameters()` is a way to do it, but you may need to use some of the visitors to compute which elements of `model.parameters()` correspond to which layers.  When #2777 is merged, operations like what you are trying to do should be a lot easier. :+1:

**Comment by FabioMBB** [comment]
Thank you very much Ryan, for confirming that model.parameters() is the way to go.

Have a nice day,
Fabio
