### ISSUE TITLE
Exception in mnist_cnn.cpp 

### ISSUE THREAD

**Issue by AdmiralPellaeon** [mlpack/examples#183]
I build mlpack with VS2019 x64 for Windows. I also created the needed CSV file with the data with the help of the python script from the tools directory.

I tried to run the "mnist_cnn.cpp" from this repo. Compiling works fine, but during the training an exception is thrown: "error: Mat::operator(): index out of bounds".

This is the call stack until the exception occurs:
![grafik](https://user-images.githubusercontent.com/11961230/136376100-3fdf9373-4fbc-4748-90d3-19d8341744fe.png)

Best regards

**Comment by rcurtin** [comment]
Hey @AdmiralPellaeon, thanks for the report.  What version of mlpack are you compiling against?

**Comment by dfy888** [comment]
> ```c++
>  train.row(0)
> ```



> Ah, ok, thanks for the information. I think that is the issue. mlpack-3.4.2 is pretty old now but we haven't released mlpack 4 yet because we are in the midst of a big refactoring. If you can download the latest `git master` branch from https://github.com/mlpack/mlpack and use that and compile the MNIST CNN example against that version, it should work. If you can't, then I think this should fix it, if you change these lines:
> 
> ```c++
>   // Create labels for training and validatiion datasets.
>   const mat trainY = train.row(0);
>   const mat validY = valid.row(0);
> ```
> 
> to this:
> 
> ```c++
>   // Create labels for training and validatiion datasets.
>   const mat trainY = train.row(0) + 1;
>   const mat validY = valid.row(0) + 1;
> ```
> 
> Sorry for the inconvenience! I hope we will be able to release and package a new version of mlpack soon (there is still lots of refactoring to do though).

yes,it is work!
