### ISSUE TITLE
it is solved！

### ISSUE THREAD

**Issue by dfy888** [mlpack/examples#185]

**Comment by dfy888** [comment]
Found Boost: /usr/include (found version "1.69.0") found components: unit_test_framework serialization

**Comment by dfy888** [comment]
boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用

**Comment by dfy888** [comment]
ok !  boost::serialization 未定义的引用  还要加上这个 -lboost_serialization

**Comment by rcurtin** [comment]
Awesome, glad you got the issue solved.  I will go ahead and close this then. :+1:
