### ISSUE TITLE
Mlpack tutorials on NLP related projects

### ISSUE THREAD

**Issue by Saikirannaidu225** [mlpack/examples#194]
There are only computer vision related examples in this repo. Improve the repo by adding  examples related to NLP

**Comment by Saikirannaidu225** [comment]
@kartikdutt18  please assign me this issue . I will work on it .

**Comment by kartikdutt18** [comment]
Hey @Saikirannaidu225, sure! Please feel to work on this. Is there any specific model that you are planning to add (Mentioning sample dataset and model might be useful for everyone that reads this thread). Thanks for picking this up!
