### ISSUE TITLE
Timestamps are incorrect in electricity-usage.csv

### ISSUE THREAD

**Issue by CyberShadow** [mlpack/examples#238]
https://datasets.mlpack.org/examples/electricity-usage.csv

E.g.:

11/25/2011 21:00:00,0.36,1,0,0
11/25/2011 22:00:00,0.39,1,0,0
11/25/2011 23:00:00,0.37,1,0,0
**11/25/2011** 00:00:00,0.3,1,0,0
11/26/2011 01:00:00,0.3,1,0,0
11/26/2011 02:00:00,0.26,1,0,0
11/26/2011 03:00:00,0.27,1,0,0

The date should roll over at 00:00, but it rolls over at 01:00.

**Comment by CyberShadow** [comment]
I also suggest using [ISO-8601](https://xkcd.com/1179/) for dates. Then, this error could have also been revealed by sorting the file and observing that the new order differs from the original order.

**Comment by rcurtin** [comment]
Thanks!  I fixed the file on datasets.mlpack.org. :+1:
