### ISSUE TITLE
Addition of MobileNet and architecture to load certain datasets.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/examples#40]
Hi  I wanted to contribute to this organization by adding mobilenet (implementation similar to pytorch/tensorflow with attributes such as include top).
2. Secondly, I also wanted to add models folder where models can be stored as classes and a user can directly import them and train on their dataset.
3. A Samples folder where all models would have a test script where they can be trained directly.
4. A data-loader for standard datasets such as CIFAR 10, ImageNet (Currently only MNIST [From Kaggle] is available).
The implementation would result in model project to similar directory structure as other python ML/DL libraries where user could directly import a model, specify input size, number of classes, include top etc.) making using MLPack models very easy on any dataset.
To start off, I wanted to implement mobilenet, as it has a small architecture (less parameters) compared to other architectures such as ResNets and hence might be easier to train on CPU only.
Would it be okay if I pursue this issue?

**Comment by zoq** [comment]
Hello @kartikdutt18 would be great to work on all of those point, but better to start with one, as you already pointed out. So if you like to work on MobileNets please feel free.

**Comment by kartikdutt18** [comment]
Thanks @zoq, I will start working on mobilenets.

**Comment by zoq** [comment]
Sounds good.
