### ISSUE TITLE
Adding ZFNet

### ISSUE THREAD

**Issue by codeboy5** [mlpack/examples#63]
I am working on adding ZFNet to the mlpack model zoo !!
Reference:- https://cs.nyu.edu/~fergus/papers/zeilerECCV2014.pdf

**Comment by kartikdutt18** [comment]
Hey @codeboy5, isn't it the same as alexnet with different kernel_size. If so, wouldn't a typedef with kernelsize be a better idea?
I might wrong though, looking forward to your response. Thanks.

**Comment by codeboy5** [comment]
Yeah I don't there is any major difference, but just thought to make the repo exhaustive.
Sure I will do it according to the latest format. Thanks!

**Comment by kartikdutt18** [comment]
Great. Thanks a lot.

**Comment by codeboy5** [comment]
@kartikdutt18 any idea by when would you be able to refactor, I would merge locally before a PR.
Thanks !

**Comment by kartikdutt18** [comment]
There are lot of plans that need to integrated. You can test the model and leave the PR open. Either it will get merged or I'll absorb it as part of my PR when it's approved.

**Comment by codeboy5** [comment]
Okay makes sense, just another thing, should my PR have all the format of LeNet as in the data loaders folder, examples folder or just the model as a class?

**Comment by kartikdutt18** [comment]
Ohh no, just wrap your model in the class. That PR isn't finalised so if you take stuff from there you would end up making changes for a long time. Just use the current repo. Have a single file called mnist_zfnet and add ZFnet as a class if possible or implement it as a FFN if that's more convenient to you.

**Comment by codeboy5** [comment]
Hi @kartikdutt18, does your AlexNet implementation work, I pulled it from your branch and it seems to give me a segmentation fault. Any idea what could be the reason ?

**Comment by kartikdutt18** [comment]
I think the the on GitHub had that issue, You can refer to my LeNet implementation (import and use on dataset manually, don't use the data loader[its still a WIP]). It works. For AlexNet I made some changes locally that I haven't pushed because I'll merge it as part of my restructuring. Also don't refer to that model, it has a lot of unnecessary functions.

**Comment by codeboy5** [comment]
Oh, thanks!

**Comment by codeboy5** [comment]
@kartikdutt18 LeNet one works like a charm, thanks a lot

**Comment by kartikdutt18** [comment]
Great!!!
I'll be pushing some other models that you could use as reference if you want.

**Comment by codeboy5** [comment]
I am also getting a segmentation fault on my model, could the small dimension (28*28) of images be an issue ?

**Comment by kartikdutt18** [comment]
Don't think so. I got the alexnet working once so that's not the issue. Also input size shouldn't affect model unless input size < kernel_size.

**Comment by codeboy5** [comment]
Yeah, that ends up happening, I worked it out using sizes, any other dataset that would be available in a similar format?

**Comment by kartikdutt18** [comment]
Are you sure about that? I think ZFNet works on mnist dataset. And I have trained very large modules on mnist to see if they work fine so I am thinking it should work.
If you want you can simply pad mnist dataset, though it should not be necessary.

**Comment by codeboy5** [comment]
Okay, i will take another look or wait for you to push some models.

**Comment by codeboy5** [comment]
Hi @kartikdutt18 i was done working on the model, should i push my PR or you talked about a different models repo, so should i wait for it?

**Comment by kartikdutt18** [comment]
You can push it if you want. Might be awhile before we merge them though.

**Comment by codeboy5** [comment]
@kartikdutt18 Hey, I was wondering what exactly is the difference between the Models repo and examples repo.
Which would be the appropriate repo to push this PR to?

**Comment by kartikdutt18** [comment]
This would make more sense in models repo. I plan on finishing part - 1 of restructuring in the next two days. Then after it gets merged we can merge zfnet as well. For examples repo, we would have real world examples / problems.
