### ISSUE TITLE
Switch to Internal split for LSTM examples.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/examples#79]
LSTM examples requires data that is not shuffled. Currently mlpack's internal `data split` class doesn't allow us to split data without shuffling yet. After mlpack/mlpack#2293 is merged we should be able to do that. This issue aims to make the change from the current implementation in LSTM examples to internal split.
Let me know if I need to clarify anything.
Thanks a lot.

**Comment by kartikdutt18** [comment]
Keep open please. Thanks.

**Comment by rcurtin** [comment]
#2293 is merged now, so anyone who wants to work on this can feel free.  It should be pretty straightforward (I hope! :)). :+1:

**Comment by divyanshugit** [comment]
@rcurtin I would like to work on this issue.

**Comment by rcurtin** [comment]
Sure, go ahead, open a PR when you have something working and we can review it. :+1:
