### ISSUE TITLE
VAE Model doesn't work.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/examples#84]
While working on #83, I had to test each file to see if the changes made are working fine. This is where I ran into an error : 

Run the make file to generate executable for `mnist_vae_cnn.cpp`. When you run the executable you will receive the following error on the master branch : 

`[FATAL] The output width / output height is not possible given the other parameters of the layer.`

I can try opening a PR that fixes this however I am trying to close some of my open PRs so if anyone gets to it before me that's great. Thanks.

**Comment by kartikdutt18** [comment]
Keep open please. Thanks.

**Comment by kartikdutt18** [comment]
Keep open please. Thanks.

**Comment by kartikdutt18** [comment]
With mlpack/mlpack#2436, The above error was resolved. However the model still segfaults.

**Comment by kartikdutt18** [comment]
Keep open.

**Comment by kartikdutt18** [comment]
Hmm, I'll work on this week then. Keep open till then.

**Comment by rcurtin** [comment]
I added a script to run all examples in Travis, but this one is commented out.  See #128. :+1:
