### ISSUE TITLE
Interesting examples to add to this repo.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/examples#85]
Hey everyone,

I am suggesting a list of examples that might be fun to add to this repo : 

~1. SRGAN and maybe ESRGAN.~
2. DCGAN on CelebA(This is currently implemented as a test in mlpack).
3. Examples on text classification (I am currently working on this in my spare time (time aside from my WIP PRs)).

I hope that they will make nice additions to this repo. Let me know what you think.
Thanks a ton!

**Comment by saksham189** [comment]
Nice idea! However we do not have GPU support and training times for the SRGAN might be very long.

**Comment by kartikdutt18** [comment]
> However we do not have GPU support and training times for the SRGAN might be very long.

Ahh, I understand. Maybe DCGAN example still be implemented and once bandicoot is available someone can add DCGAN as well.

**Comment by shrit** [comment]
@kartikdutt18, I would be very happy if you add a simple example that shows how we can use `LeNet` classes when your pull request https://github.com/mlpack/models/pull/3 get merged of course.
What do you think?

**Comment by kartikdutt18** [comment]
> What do you think?

Sure, that would be great. I think it's near completion hopefully, it gets merged this week.

**Comment by shrit** [comment]
Keep open

**Comment by kartikdutt18** [comment]
Hey @hello-fri-end, Feel free to do so. Also If I remember correctly, the code for this is currently available as comments in mlpack tests.

**Comment by hello-fri-end** [comment]
@kartikdutt18 : Cool! I'll take a look at that.

**Comment by hello-fri-end** [comment]
Hey @kartikdutt18, where can I find CelebA dataset in .csv format? I can only find .png or .jpg files online. Is there a way to load image data into an armadillo matrix, i couldn't find anything in the documentation..

**Comment by aayushsinha0706** [comment]
Hello mlpack community, I would like to add an example multiple disease prediction system, currently the examples in repository are single disease based.

**Comment by shrit** [comment]
Closing this issue since this has a bit deprioritized
