### ISSUE TITLE
Adding Clang format support for this repository

### ISSUE THREAD

**Issue by shrit** [mlpack/examples#88]
Hello, 

I have noticed that there was an issue and a pull request has been opened last year in mlpack main repository using clang for code formatting https://github.com/mlpack/mlpack/issues/1203 https://github.com/mlpack/mlpack/pull/1205.
Following the discussion, it seems that clang-format was not a good option, especially the integration issue with Jenkins (if I understood well).
However, It should be more comfortable for contributors and for reviewers if clang-format is in place, even if it is not integrated automatically with continuous integration systems. In fact, in most cases, there will be modifications requested by the reviewers from the contributors.
For example, if a contributor has missed some styles, a reviewer will ask him just to apply the clang-format existed in this repository, rather than losing energy from both sides to verify that all styles are well in place. I would like to have some feedback on this idea, for me, this repository and the [model](https://github.com/mlpack/models) repository are well situated for clang-format experiment especially that the code base still small comparing to mlpack or ensmallen

**Comment by ShikharJ** [comment]
I personally prefer the use of a custom linting script to take care of code styling issues. It's not a great solution for the bigger `mlpack` repository, but should be fine for `ensmallen`/`models`/`examples` and so on.

**Comment by shrit** [comment]
@ShikharJ I totally agree with you. Would you mind opening a pull request in this repository with the same script you have built 2 years ago for mlpack?

**Comment by ShikharJ** [comment]
@shrit Please feel free to replicate that script, sorry for the late reply.

**Comment by shrit** [comment]
Perfect, I have created a pull request, please feel free to review it

**Comment by shrit** [comment]
This will be closed after https://github.com/mlpack/examples/pull/89
